name: luthor_example
description: An example package for luthor
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  luthor: ^1.0.0 # Configured via catalog

dev_dependencies:
  lints: ^6.1.0 # Configured via catalog
