name: luthor_annotation
description: Annotation for luthor_generator
version: 0.3.1
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor_annotation
homepage: https://luthor.netlify.app

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.1
  test: ^1.25.1
