name: luthor_forms
description: Easy to use form validation and submission for Dart and Flutter applications using Luthor for validation.
version: 0.0.1
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor_forms

environment:
  sdk: ^3.4.4

dependencies:
  bloc: ^8.1.4
  luthor: ^0.4.2

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
