name: luthor
description: |
  A Dart validation library inspired by https://zod.dev 
  with support for code generation.
version: 1.0.0
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor
homepage: https://luthor.ex3.dev
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  meta: ^1.17.0 # Configured via catalog

dev_dependencies:
  lint: ^2.12.0 # Configured via catalog
  test: ^1.31.1 # Configured via catalog
