builders:
  luthor:
    import: "package:luthor_generator/builder.dart"
    builder_factories: ["luthorBuilder"]
    build_extensions: { ".dart": [".luthor.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

targets:
  $default:
    sources:
      - lib/**
      - test/**
      - $package$
