name: docs
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jaspr: ^0.12.0
  jaspr_riverpod: ^0.3.11
  jaspr_router: ^0.4.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  custom_lint: ^0.6.4
  jaspr_builder: ^0.12.0
  jaspr_tailwind: ^0.1.1
  lint: ^2.3.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

jaspr:
  mode: static
